### ISSUE TITLE
uff.model.exceptions.UffException: Const node conversion requested, but node is not Const

### ISSUE THREAD

**Issue by gftd** [tensorflow/tensorrt#152]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/convert-to-uff", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/uff/bin/convert_to_uff.py", line 92, in main
    debug_mode=args.debug
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 178, in from_tensorflow
    debug_mode=debug_mode)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 79, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 47, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter_functions.py", line 539, in convert_bias_add
    kwargs["tf_nodes"][biases_name])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 122, in convert_tf2numpy_const_node
    raise UffException("Const node conversion requested, but node is not Const\n" + str(tf_node))
uff.model.exceptions.UffException: Const node conversion requested, but node is not Const
name: "gru_1/while/BiasAdd_1/Enter"
op: "Enter"
input: "gru_1/strided_slice_7"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "frame_name"
  value {
    s: "gru_1/while/while_context"
  }
}
attr {
  key: "is_constant"
  value {
    b: true
  }
}
attr {
  key: "parallel_iterations"
  value {
    i: 32
  }
}

**Comment by colin-zhou** [comment]
encounter the same problem.

**Comment by pooyadavoodi** [comment]
This repository is not for UFF (it's only for TF-TRT). Please report this failure in https://devtalk.nvidia.com/default/board/304/tensorrt/

**Comment by maodou-shushu** [comment]
Is the problem solved?
I have the same problem.
