### ISSUE TITLE
image_classification test fails

### ISSUE THREAD

**Issue by antoajayraj** [tensorflow/tensorrt#53]
Trying to run the examples in tensorrt fails with the following error

# python image_classification.py
Traceback (most recent call last):
  File "image_classification.py", line 30, in <module>
    import official.resnet.imagenet_main
  File "/root/antojohn/tensorrt/tftrt/examples/third_party/models/official/resnet/imagenet_main.py", line 31, in <module>
    from official.resnet import resnet_run_loop
  File "/root/antojohn/tensorrt/tftrt/examples/third_party/models/official/resnet/resnet_run_loop.py", line 41, in <module>
    from official.utils.misc import distribution_utils
  File "/root/antojohn/tensorrt/tftrt/examples/third_party/models/official/utils/misc/distribution_utils.py", line 28, in <module>
    None: tf.distribute.experimental.CollectiveCommunication.AUTO,
AttributeError: 'module' object has no attribute 'experimental'

Any thoughts/suggestions ?

**Comment by pooyadavoodi** [comment]
This might be resolved according to https://github.com/tensorflow/models/issues/6526
Could you double check please.

**Comment by pooyadavoodi** [comment]
Closing. Please reopen in case the issue remains.
