### ISSUE TITLE
Error with object-detection examples when using batch size > 1 related to image size

### ISSUE THREAD

**Issue by mankeyboy** [tensorflow/tensorrt#92]
@pooyadavoodi @trevor-m When using batch sizes > 1, the latest object-detection code asks to give a fixed image shape but when I provide it with [600,600], it fails with a seg-fault. 
This is the error I'm seeing:
```
Traceback (most recent call last):
  File "/home/mayroy13/anaconda3/envs/trt-py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mayroy13/anaconda3/envs/trt-py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mayroy13/Mayank/Mayank/test/tensorrt/tftrt/examples/object_detection/test.py", line 105, in <module>
    test(args.test_config_path)
  File "/home/mayroy13/Mayank/Mayank/test/tensorrt/tftrt/examples/object_detection/test.py", line 81, in test
    **test_config['benchmark_config'])
  File "/home/mayroy13/Mayank/Mayank/test/tensorrt/tftrt/examples/object_detection/object_detection.py", line 641, in benchmark_model
    feed_dict={tf_input: batch_images})
  File "/home/mayroy13/anaconda3/envs/trt-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/mayroy13/anaconda3/envs/trt-py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (104, 600, 600, 3) for Tensor 'image_tensor:0', which has shape '(128, ?, ?, 3)'
```

The json file I'm using to call the test module with is:

```
{
  "model_config": {
    "model_name": "ssd_inception_v2_coco",
    "output_dir": "models",
    "override_nms_score_threshold": 0.3,
    "batch_size": 128
  },
  "optimization_config": {
    "use_trt": true,
    "precision_mode": "FP16",
    "output_path":"engine_dir/ssd_inception_v2_b128_fp16.pb",
    "force_nms_cpu": true,
    "replace_relu6": true,
    "remove_assert": true
  },
  "benchmark_config": {
    "images_dir": "coco/val2017",
    "annotation_path": "coco/annotations/instances_val2017.json",
    "batch_size": 128,
    "image_shape":[600,600],
    "num_images": 1000,
    "output_path": "stats/ssd_inception_v2_coco_trt_fp16_b128.json"
  },
  "assertions": [
    "statistics['map'] > (0.268 - 0.005)"
  ]
}
```

Hoping anyone here can help me sort this error out.

**Comment by trevor-m** [comment]
As a workaround, you can set your num_images in the config to a multiple of 128 such as 1024.

**Comment by mankeyboy** [comment]
The rest of the info in that json is correct then, I assume? I'll try this workaround and see.
